### PR TITLE
update to 2.0.1

### PR DESCRIPTION
**Pull request by synapticarbors**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

It looks like the auto update bot isn't working maybe because of the erroneous 2.5.1 release. I've added this one manually and will do `2.1.0` as well if this is approved. I've switched it to `noarch: python` and also added `pip check` to the tests.

@conda-forge-admin please rerender

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin please rerender

**Comment by yarikoptic** [comment]
Thank you @synapticarbors ! Got here alerted by @CodyCBakerPhD  at https://github.com/conda-forge/nwbinspector-feedstock/pull/8 .

> the erroneous 2.5.1 release.

shows that 2.5.1 was "yanked".  I guess might indeed have confused something

> I've added this one manually and will do `2.1.0` as well if this is approved. 

FWIW I would not mind straight update to 2.1.0 ;)  currently test seems to die with `/test_tmp/run_test.sh: line 7:   298 Killed                  python ./test.py` -- not sure for what reason besides may be flooding with all the `PendingDeprecationWarning`s

> I've switched it to `noarch: python`

hm, where?  I see that you removed `--no-deps` , what is the reason?  I thought that it is desired to not ship then all dependencies within this package itself and I see it used in majority if not all of feedstocks I have handy locally.

>  and also added `pip check` to the tests.

cool

**Comment by synapticarbors** [comment]
I had initially changed it to `noarch: python`, but then switched it back since I saw some discussion in past issues and didn't want to introduce something new that possibly went against what the feedstock maintainers wanted. 

I removed the `--no-dep` so that the line matches up with the current recommended call structure from:
https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml#L38

I wanted to not immediately jump to `2.1.0` since another recipe in staged-recipes that I was reviewing explicitly pinned to `2.0.1`, which is how I ended up looking at this feedstock.

I'm going to look into the errors and see if I can figure out how to get this to build.

**Comment by synapticarbors** [comment]
The error on windows is perhaps a bit more informative:

```
OSError: [WinError 1455] The paging file is too small for this operation to complete
```
I think this has something to do with the CI instance running out of memory. Is it possible to skip the tests and just check for correct import of the package? Or is there a more limited set tests that could be run instead of the whole test suite that has a smaller footprint?

**Comment by CodyCBakerPhD** [comment]
> I think this has something to do with the CI instance running out of memory. Is it possible to skip the tests and just check for correct import of the package? Or is there a more limited set tests that could be run instead of the whole test suite that has a smaller footprint?

@rly or @oruebel would probably know more about

**Comment by rly** [comment]
Test are failing because PyNWB depends on HDMF, the latest version of HDMF issues a number of  `PendingDeprecationWarning`s, and some tests in the test suite count the number of warnings raised for a particular line of code and check that the number is as expected. These are not future-proof tests. PyNWB 2.0.1 works with this version of HDMF, but the test suite fails. While we resolve that issue in PyNWB, I suggest removing the requirement that `python test.py` passes (only the import pynwb and `pip check` tests will run).

**Comment by rly** [comment]
Tests may also be failing due to a memory issue, but that is separate and cannot be disentangled just yet.

**Pull request merged**
