### PR TITLE
1.0.3

### PR DESCRIPTION
**Pull request by rly**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rly** [comment]
@conda-forge-admin, please update team

**Comment by rly** [comment]
@conda-forge-admin, please rerender

**Comment by rly** [comment]
@conda-forge/core could you please add me to the conda-forge team pynwb? I tried to use the "please update team" command, but did not receive an email inviting me onto the team. Thank you.

**Comment by isuruf** [comment]
@rly, you'll be added to the team after one of the current maintainers merge this PR.

**Comment by rly** [comment]
@isuruf Ah, I see. Thank you.

@ajtritt @oruebel @bendichter Please merge when you get a chance. Thanks.

**Pull request merged**
