### PR TITLE
Release 2.5.0 with builds for linux / aarch and linux / ppc64le

### PR DESCRIPTION
**Pull request by rly**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rly** [comment]
@conda-forge-admin, please rerender

**Comment by rly** [comment]
The CI is failing because of https://github.com/hdmf-dev/hdmf/issues/889 . Ideally we fix that before merging this.

**Comment by rly** [comment]
@conda-forge-admin, please rerender

**Comment by mavaylon1** [comment]
Could you explain what is this for beyond the scope of the release? @rly

**Comment by rly** [comment]
@mavaylon1 this addresses https://github.com/NeurodataWithoutBorders/pynwb/issues/1714 - sorry I forgot to tag that!

**Pull request merged**
