### PR TITLE
establish building/testing across different environments

### PR DESCRIPTION
**Pull request by yarikoptic**
@conda-forge-admin please rerender

#25 already included a commit 3a7074be093f6a102bcafda653fde4e5fde93deb which removed `noarch`

TODOs
- [x] assure that building/testing goes is done on separate platforms
- [x] remove empty commit after rerendering

### CODE REVIEW

**Comment by yarikoptic** [comment]
so, re-rendering triggered build across all environments and all is good on linux&osx but windows have an issue, which is strangely is triggered AFTER successfully passing the tests.

<details>
<summary>here is a copy/paste from one of the runs (click to expand)</summary> 

```shell
OK
............................................................................................................................................................................======================================================================
2020-02-04 18:05:03,634 - INFO - Ran 172 tests - OK

(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit /B 1 

(%PREFIX%) %SRC_DIR%>exit /B 0 

(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit 1 

Resource usage statistics from testing pynwb:
   Process count: 2
   CPU time: Sys=0:00:00.4, User=0:00:15.0
   Memory: 84.6M
   Disk usage: 1.6M
   Time elapsed: 0:00:18.1

TEST END: D:\bld\win-64\pynwb-1.2.1-py38_0.tar.bz2
Renaming work directory,  D:\bld\pynwb_1580839262356\work  to  D:\bld\pynwb_1580839262356\work_moved_pynwb-1.2.1-py>=3_0_win-64_main_build_loop
Traceback (most recent call last):
  File "C:\Miniconda\lib\shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\bld\\pynwb_1580839262356\\work' -> 'D:\\bld\\pynwb_1580839262356\\work_moved_pynwb-1.2.1-py>=3_0_win-64_main_build_loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 2409, in build_tree
    shutil.move(metadata.config.work_dir, dest)
  File "C:\Miniconda\lib\shutil.py", line 555, in move
    symlinks=True)
  File "C:\Miniconda\lib\shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "C:\Miniconda\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\bld\\pynwb_1580839262356\\work_moved_pynwb-1.2.1-py>=3_0_win-64_main_build_loop'
##[error]Cmd.exe exited with code '1'.
Finishing: Build recipe
```
</details>

not yet sure if that is anyhow pynwb issue or conda-forge's scripts

**Comment by yarikoptic** [comment]
@conda-forge-admin please rerender

so it accounts for new python skip statement (currently builds for python 2.7 as well)

**Comment by yarikoptic** [comment]
ok, all green, and no push back from conda-forge people when I described why I needed `noarch` to be removed (testing across environments).
So, if this PR is accepted -- in the future, when a new environment (e.g., a new python version) is added, conda-forge scripts need to be re-rendered to include it to provide build for it.  Benefit: no pynwb for possibly incompatible environments.

**Comment by rly** [comment]
~~This looks good to me, although I am surprised that tests pass on python 2.7... PyNWB uses a few Python 3 only features, such as use of the argument-less `super()` and "new-style" classes.~~

@yarikoptic Was there a particular reason to not run the pynwb integration tests as well? They take up more CI resources but may reveal problems of pynwb writing to / reading from the filesystem.

**Comment by rly** [comment]
Never mind my comment about Python 2.7.... I was also looking at the tests in #27.

**Comment by yarikoptic** [comment]
I simply do not know how to run integration tests and surprised that they are not ran by default (not to say that I need to use a custom runner instead of e.g. `nose` or `pytest` or just `python -m unittest`). learn everything each day ;)  please push addition of running also integration tests, I would also love to add it to debian package (unless it requires additional downloads at test runtime which is not allowed for debian package building)

**Comment by yarikoptic** [comment]
@rly -- done with the @ajtritt guidance! ;)

**Comment by yarikoptic** [comment]
woohoo -- all green, so is ready for a nice merge, so that the next release would be built with testing (or we could boost build number here to provide a new build of current pynwb package, but I do not think it is worth it)

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
Great! Looks good.

**Pull request merged**
